version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:chakracore-10.13
      - image: circleci/mongo:4.0.0

    working_directory: ~/repo

    steps:
      - checkout

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: NODE_ENV=test
      - run: yarn test